# Generated by Django 2.1.2 on 2018-10-03 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0002_auto_20181003_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotmark',
            old_name='ts',
            new_name='content_id',
        ),
    ]
