# Generated by Django 2.1.1 on 2018-10-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0006_auto_20181003_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='areacode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='sigungucode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
